name: Terraform Deploy #워크플로우 이름
# main 브랜치에 push가 발생하면 아래 워크플로우가 자동으로 실행
# 코드를 main에 푸시하면 Terraform이 실행
# .github/workflows/terraform.yml

# .github/workflows/terraform.yml
# .github/workflows/terraform.yml
on:
  push:
    branches:
      - main  # main 브랜치에 push될 때만 apply
    paths:
      - '**.tf'
      - '**/terraform.*'
  pull_request:

jobs:
  terraform:
    name: Terraform Init, Plan and Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2
      TF_VAR_create_jenkins_instance : true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Create Trivy report directory
        run: mkdir -p report

      - name: Run SCA (e.g., Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          exit-code: 1
          format: table
          output: ./report/trivy-results.txt
          scan-ref: .
          ignore-unfixed: false
          vuln-type: os,library
          cache-dir: ./.cache/trivy
          list-all-pkgs: false
          version: v0.64.1
          cache: true
          skip-setup-trivy: false

          # cache dir 내용 수정
      - name: Upload Trivy Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: ./report/trivy-results.txt

      - name: Generate CycloneDX SBOM with Syft
        uses: anchore/sbom-action@v0.15.4
        with:
          format: cyclonedx-json
          output-file: sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  build:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Your Build Step Here
        run: echo "Build Passed"

